#!/usr/bin/env groovy

/**
 * It requires the following Jenkins plugins to work:
 * - Warnings Next Generation
 * - JUnit Plugin
 * - valgrind
 */

pipeline {

	agent none

	stages
	{
		stage('Platforms')
		{
			parallel
			{
				%for platform, config in configs%
					%for buildName, options in config.builds%

						stage('%platform%%if buildName%.%buildName%%end%')
						{
							agent
							{
								dockerfile
								{
									filename '%config.dockerfilePath%'
								}
							}
							stages
							{
								stage('Build %platform%%if buildName%.%buildName%%end%')
								{
									steps
									{
										sh './app.py update'
										sh './app.py init'
										sh './app.py build %for moduleId, buildConfig in options.configs% -c %moduleId%:%buildConfig% %end%'
									}
								}
								%if options.tests and not options.lint%
									stage('Test %platform%%if buildName%.%buildName%%end%')
									{
										steps
										{
											%if not options.memleaks%
												sh "./app.py run %for test in options.tests% --cmd '%test%' %end% -j0"
											%end%

											%if options.memleaks%
												sh "./app.py run %for index, test in options.tests% --cmd 'valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --gen-suppressions=all --suppressions=%options.valgrindSuppPath% --xml=yes --xml-file=%buildName%_tests_%index%_valgrind.xml %test%' %end% -j0"
											%end%
										}
									}
								%end%
							}
							post
							{
								always
								{
									// Publish the warnings from the various compiler or static analyzers
									%if options.compiler == "clang"%
										recordIssues enabledForFailure: true, aggregatingResults: true, tools: [clang(), clangTidy()]
									%end%
									%if options.compiler == "gcc"%
										recordIssues enabledForFailure: true, aggregatingResults: true, tools: [gcc4()]
									%end%
									%if options.compiler == "cppcheck"%
										recordIssues enabledForFailure: true, aggregatingResults: true, tools: [cppCheck()]
									%end%

									// Publish junit test reports
									%if options.junit%
										junit '*_junit.report'
									%end%

									%if options.memleaks%
										publishValgrind(pattern: '*_valgrind.xml', failThresholdInvalidReadWrite: '0', failThresholdDefinitelyLost: '0', failThresholdTotal: '0', unstableThresholdInvalidReadWrite: '0', unstableThresholdDefinitelyLost: '0', unstableThresholdTotal: '0', sourceSubstitutionPaths: '0', publishResultsForAbortedBuilds: true, publishResultsForFailedBuilds: true, failBuildOnMissingReports: true, failBuildOnInvalidReports: true)
									%end%
								}
							}
						}
					%end%
				%end%
			}
		}
	}
}
